server:
  port: 8081

inventory:
  url: http://localhost:8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/order_service
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: none

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs